name: portfolio

on:
  push:
    branches:
      - main
  pull_request:
    branches: [ main ]  
      # note that your "main" branch might be called main instead of master

jobs:
  pipeline_jobs:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: '16'
      - name: install node packages
        run: npm install
      - name: lint
        run: npm run lint
      - name: test
        run: npm run test -- --verbose 2>&1 | tee test.log      